# Generated by Django 4.2 on 2024-02-19 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "PUBLISHED"),
                    ("pending", "PENDING"),
                    ("archive", "ARCHIVE"),
                    ("trash", "TRASH"),
                ],
                default="pending",
                help_text="Status",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
