# Generated by Django 4.2 on 2024-02-24 15:07

import django.db.models.deletion
from django.db import migrations, models

import blog.models.media


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_comment_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "IMAGE"),
                            ("audio", "AUDIO"),
                            ("video", "VIDEO"),
                        ],
                        default="image",
                        help_text="File Type",
                        max_length=25,
                    ),
                ),
                (
                    "media",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=blog.models.media.author_title_upload_path,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medias",
                        to="blog.post",
                    ),
                ),
            ],
        ),
    ]
