# Generated by Django 4.2 on 2024-02-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Media",
            new_name="ProductMedia",
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("created_at",),
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterModelOptions(
            name="productprice",
            options={
                "ordering": ("effective_date",),
                "verbose_name": "Product Price",
                "verbose_name_plural": "Product Prices",
            },
        ),
    ]
